### ISSUE TITLE
INFOGRAFIA DE LA GESTION DE PROYECTOS DE SOFTWARE_RIGOBERTORAMIREZNICOLAS

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/infografia-Rigoberto2001#2]
![INFOGRAFIA_FASESDELAGESTPROYSOFTWARE_RIGOBERTORAMIREZNICOLAS](https://user-images.githubusercontent.com/79929662/132294653-8caf61b3-0459-4a46-9d9c-8daa9726fb45.png)

**Comment by Nayee123** [comment]
Calificación : 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
